BBPATH .= ":${LAYERDIR}"
BBFILES += "${LAYERDIR}/recipes-*/*/*.bb ${LAYERDIR}/recipes-*/*/*.bbappend"
BBFILE_COLLECTIONS += "headless"
BBFILE_PATTERN_headless = "^${LAYERDIR}/"
BBFILE_PRIORITY_headless = "10"
LAYERDEPENDS_headless = "core st-openstlinux stm-st-stm32mp"
LAYERSERIES_COMPAT_headless = "scarthgap"
