require conf/distro/openstlinux-weston.conf
DISTRO = "stm32mp-headless"
DISTRO_NAME = "STM32MP257F-DK headless Linux"
DISTRO_FEATURES:remove = "x11 wayland opengl vulkan opencl openvx kde splashscreen"
MACHINE_FEATURES:remove = "gpu openvx opencl vulkan splashscreen"
